"""
Module for parsing real-world university dataset (Okan University).
Uses pandas to clean and map raw Excel exports into the CSP domain architecture.
"""

import pandas as pd
from collections import defaultdict
from src.models.domain import Exam, TimeSlot, Room, Instructor, ProblemInstance


def parse_okan(
    student_excel_path: str,
    schedule_excel_path: str,
    exams_sheet_name: str = "FINAL(8-18 OCAK)"
) -> ProblemInstance:
    """
    Parses messy real-world Excel files and builds a ProblemInstance.
    Handles heterogeneous exam modes (online vs. face-to-face) via Virtual Rooms.
    """

    print("Reading data from Excel files...")

    # ==========================================
    # STEP 1: Parse Rooms & Create Virtual Room
    # ==========================================
    # Read the capacities sheet directly from the Excel file
    df_rooms = pd.read_excel(schedule_excel_path, sheet_name="DERSLİK KAPASİTE")
    
    rooms = []
    room_name_to_id = {}
    room_id_counter = 0

    for index, row in df_rooms.iterrows():
        room_name = str(row.iloc[0]).strip()
        capacity = row.iloc[1]
        
        # Skip empty rows (NaN values) generated by Excel formatting
        if pd.isna(room_name) or room_name == 'nan':
            continue
            
        # Extract numerical capacity from mixed strings (e.g., "24 (Çizim Masalı)" -> 24)
        if isinstance(capacity, str):
            capacity = int(''.join(filter(str.isdigit, capacity)))
            
        rooms.append(Room(id=room_id_counter, capacity=int(capacity)))
        room_name_to_id[room_name] = room_id_counter
        room_id_counter += 1

    # Define the Virtual Room with infinite capacity for ONLINE exams
    VIRTUAL_ROOM_ID = 999
    rooms.append(Room(id=VIRTUAL_ROOM_ID, capacity=100000))

    # ==========================================
    # STEP 2: Parse Instructors & Dual-Roles
    # ==========================================
    # Read the off-days sheet to extract instructor list and titles
    df_inst = pd.read_excel(schedule_excel_path, sheet_name="İZİN GÜNLERİ")
    
    instructors = []
    inst_name_to_id = {}
    inst_id_counter = 0

    for index, row in df_inst.iterrows():
        if 'UNVAN/ AD SOYAD' not in df_inst.columns:
            continue
            
        raw_name = str(row['UNVAN/ AD SOYAD']).strip()
        if pd.isna(raw_name) or raw_name == 'nan':
            continue
            
        # Detect Dual-Role: If the title contains "AR. GÖR", they are considered PhD students
        is_phd = "AR. GÖR" in raw_name.upper()
        
        # Initialize default preferences (True = available for all slots initially)
        prefs = {} 
        
        instructors.append(Instructor(id=inst_id_counter, is_phd=is_phd, preferences=prefs))
        inst_name_to_id[raw_name] = inst_id_counter
        inst_id_counter += 1

    # ==========================================
    # STEP 3: Parse Exam Schedule
    # ==========================================
    # Read the main exam schedule sheet
    df_exams = pd.read_excel(schedule_excel_path, sheet_name=exams_sheet_name)
    
    timeslots = []
    exams_metadata = {} # Stores temporary attributes (is_online, lecturer_id) mapped by course_code
    timeslot_map = {} 
    ts_id_counter = 0
    valid_exam_codes = []

    for index, row in df_exams.iterrows():
        course_code = str(row.get('Ders Kodu', '')).strip()
        
        # Skip invalid or empty course codes
        if pd.isna(course_code) or course_code == 'nan' or course_code == 'None' or course_code == '':
            continue
            
        valid_exam_codes.append(course_code)
            
        date_str = str(row.get('Gün', '')).strip()
        time_str = str(row.get('Saat', '')).strip()
        room_str = str(row.get('Derslik', '')).strip().upper()
        
        # Map unique date/time combinations to an integer timeslot ID
        ts_key = f"{date_str}_{time_str}"
        if ts_key not in timeslot_map:
            ts_day = ts_id_counter // 5 
            ts_period = ts_id_counter % 5
            timeslots.append(TimeSlot(id=ts_id_counter, day=ts_day, period=ts_period))
            timeslot_map[ts_key] = ts_id_counter
            ts_id_counter += 1
            
        # Flag if the exam is online to route it to the Virtual Room later
        is_online = "ONLINE" in room_str or "ON LINE" in room_str
        
        # Map lecturer name to instructor ID (Fallback to 0 if not found)
        lecturer_name = str(row.get('Öğretim Elemanı', '')).strip()
        lecturer_id = inst_name_to_id.get(lecturer_name, 0) 
        
        # Store attributes for object instantiation in Step 5
        exams_metadata[course_code] = {
            "is_online": is_online,
            "lecturer_id": lecturer_id
        }

    # ==========================================
    # STEP 4: Parse Students (Conflict Graph Base)
    # ==========================================
    # Read student enrollments to build exact H1 relationships
    df_students = pd.read_excel(student_excel_path)
    
    exam_students_map = defaultdict(set)
    
    for index, row in df_students.iterrows():
        if 'Ders Kodu' not in df_students.columns or 'Öğrenci No' not in df_students.columns:
            continue
            
        course_code = str(row['Ders Kodu']).strip()
        student_id = row['Öğrenci No']
        
        # Map students only to courses that actually have a scheduled exam
        if course_code in valid_exam_codes and not pd.isna(student_id):
            exam_students_map[course_code].add(int(student_id))

    # ==========================================
    # STEP 5: Assemble Final Exam Objects
    # ==========================================
    exams = []
    exam_id_counter = 0
    
    for course_code in valid_exam_codes:
        students = exam_students_map.get(course_code, set())
        
        # Edge case: If an exam has no students, add a dummy to prevent domain validation errors
        if len(students) == 0:
            students.add(999999) 
            
        # Dynamically calculate required invigilators based on student count
        req_invig = max(1, len(students) // 40)
        
        meta = exams_metadata.get(course_code, {"is_online": False, "lecturer_id": 0})
        
        exam_obj = Exam(
            id=exam_id_counter,
            student_ids=students,
            lecturer_id=meta["lecturer_id"], 
            required_invigilators=req_invig,
            is_online=meta["is_online"]
        )
        exams.append(exam_obj)
        exam_id_counter += 1

    print(f"Parsing complete. Found {len(exams)} exams, {len(rooms)} rooms, {len(instructors)} instructors.")

    return ProblemInstance(
        exams=exams,
        timeslots=timeslots,
        rooms=rooms,
        instructors=instructors
    )